[workspace]
# Git configuration
git_tag_name = "{{ package_name }}-v{{ version }}"
git_release_enable = true

# Changelog configuration
changelog_update = true
changelog_path = "{{ package_name }}/CHANGELOG.md"

# Changelog generation
[changelog]
# Use git-cliff for changelog generation
config = "cliff.toml"