name: Security Audit

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit

      - name: Install cargo-outdated
        uses: taiki-e/install-action@cargo-outdated

      - name: Install cargo-machete
        uses: taiki-e/install-action@cargo-machete

      - name: Run security audit
        run: cargo audit

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1

      - name: Check for unused dependencies
        run: cargo machete
