name: Security Audit

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-audit
        uses: actions-rs/install@v1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true

      - name: Install cargo-outdated
        uses: actions-rs/install@v1
        with:
          crate: cargo-outdated
          version: latest
          use-tool-cache: true

      - name: Install cargo-machete
        uses: actions-rs/install@v1
        with:
          crate: cargo-machete
          version: latest
          use-tool-cache: true

      - name: Run security audit
        run: cargo audit

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1

      - name: Check for unused dependencies
        run: cargo machete
